name: 同步上游节点 # 监听上游仓库文件变动

on:
  # 你可以手动触发
  workflow_dispatch:

  # 也可以定时同步（每6小时）
  # 分钟 小时 天 月  周
  # https://crontab.guru/
  #schedule:
  #  - cron: '0 0 * * *'

jobs: # 创建环境
  sync-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: 检出自己的仓库(存储状态和结果)
        uses: actions/checkout@v4
        with:
          repository: cfv2ray/subCollection
          token: ${{ secrets.HEXO_AUTO_DEPLOY }}
          path: own_repo
      
      # if [ ! -s free-nodes.md ]; then -s 测试文件是否存在且大小大于0
      # 文件不存在或大小为0
      - name: 下载free-nodes/v2rayfree的README.md
        id: fetch_readme
        run: |
          curl -s -L "https://raw.githubusercontent.com/free-nodes/v2rayfree/refs/heads/main/README.md" -o README.md
          if [ ! -s README.md ]; then 
            echo "README.md 下载失败或为空"
            exit 1
          fi
          echo "README.md 下载成功"

      # 下载，失败则退出
      # 提取以该前缀开头的第一行（整行）
      # grep -o "https://[^ ]*" 
      # 从输入中提取第一个以 https:// 开头，后面紧跟任意多个非空格字符的字符串，匹配以空格结尾；
      # -o：只输出匹配到的部分，而不是输出整行。
      # 默认 grep 会输出包含匹配的整行，加上 -o 后仅显示匹配的文本本身。
      # head -1：只取第一行（如果有多行匹配）。
      # sed 's/$//'`：将行尾的反引号替换为空。
      # LATEST_TAG=${LATEST_TAG%`}   # 注意反引号需要转义或特殊处理 也可以去掉`
      - name: 从README.md中提取目标链接
        id: extract_url
        run: |
          url='https://raw.githubusercontent.com/free-nodes/v2rayfree/main/README.md'
          PREFIX='https://raw.githubusercontent.com/free-nodes/v2rayfree/main/'
          content=$(curl -s --fail "$url") || { echo "Error: failed to download $url"; exit 1; }
          LATEST_TAG=$(echo "$content" | grep -F "$PREFIX"  | head -1 | grep -o "https://[^ ]*" | sed 's/`$//')
          if [ -z "$LATEST_TAG" ]; then
            echo "未找到下载链接"
          else
            echo "下载链接: $LATEST_TAG"
          fi
          
          curl -s -L --fail "$LATEST_TAG" -o free-nodes || { echo "下载失败"; exit 1; }
          echo "下载完成，保存为 free-nodes"

      