name: 同步上游节点 # 监听上游仓库文件变动

on:
  # 你可以手动触发
  workflow_dispatch:

  # 也可以定时同步（每6小时）
  # 分钟 小时 天 月  周
  # https://crontab.guru/
  #schedule:
  #  - cron: '0 0 * * *'

jobs: # 创建环境
  sync-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: 检出自己的仓库(存储状态和结果)
        uses: actions/checkout@v4
        with:
          repository: cfv2ray/subCollection
          token: ${{ secrets.HEXO_AUTO_DEPLOY }}
          path: own_repo
      
      # if [ ! -s free-nodes.md ]; then -s 测试文件是否存在且大小大于0
      # 文件不存在或大小为0
      - name: 下载free-nodes/v2rayfree的README.md
        id: fetch_readme
        run: |
          curl -s -L "https://raw.githubusercontent.com/free-nodes/v2rayfree/refs/heads/main/README.md" -o README.md
          if [ ! -s README.md ]; then 
            echo "README.md 下载失败或为空"
            exit 1
          fi
          echo "README.md 下载成功"

      # 定义需要匹配的前缀（可根据实际情况修改） 
      # 从 README.md 中查找包含该前缀的行，并提取整行内容（假设整行就是 URL）
      # 如果该行前缀后面还有其他内容，需要调整提取逻辑  
      - name: 从README.md中提取目标链接
        id: extract_url
        run: |
          url='https://raw.githubusercontent.com/free-nodes/v2rayfree/main/README.md'
          LATEST_TAG=$(curl -s $url | grep -E '^https://raw\.githubusercontent\.com/free-nodes/v2rayfree/main/' | head -1)
          echo "LATEST_TAG: $LATEST_TAG"