name: 同步上游仓库文件 # 监听上游仓库文件变动

on:
  # 你可以手动触发
  workflow_dispatch:

  # 也可以定时同步（每6小时）
  # 分钟 小时 天 月  周
  # https://crontab.guru/
  # 北京时间=UTC时间+8
  schedule:
    - cron: '0 7 * * *' # 这是北京时间下午15:00

jobs: # 创建环境
  sync-changed-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送代码

    steps:
      - name: 检出自己仓库代码
        uses: actions/checkout@v4

      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'


      - name: 获取当前日期（年、月、日）
        id: date
        run: |
          echo "year=$(date +%Y)" >> $GITHUB_OUTPUT
          echo "month=$(date +%m)" >> $GITHUB_OUTPUT
          echo "day=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
      
      # 下载https://shareclash.github.io上面的节点文件
      - name: 下载文件（自动拼接日期）
        run: |
          URL="https://node.freeclashnode.com/uploads/${{ steps.date.outputs.year }}/${{ steps.date.outputs.month }}/0-${{ steps.date.outputs.day }}.txt"
          echo "下载地址：$URL"
          # 下载并保存为 clashgithub
          curl -L \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            --insecure \
            -o clashgithub \
            "$URL"
      
      # 从https://github.com/free-nodes/v2rayfree上下载节点文件
      - name: 从readme.md中找下载链接并下载文件
        run: |
          url='https://raw.githubusercontent.com/free-nodes/v2rayfree/main/README.md'
          PREFIX='https://raw.githubusercontent.com/free-nodes/v2rayfree/main/'
          content=$(curl -s --fail "$url") || { echo "Error: failed to download $url"; exit 1; }
          LATEST_TAG=$(echo "$content" | grep -F "$PREFIX"  | head -1 | grep -o "https://[^ ]*" | sed 's/`$//')
          if [ -z "$LATEST_TAG" ]; then
            echo "未找到下载链接"
          else
            echo "下载链接: $LATEST_TAG"
          fi
          
          curl -s -L --fail "$LATEST_TAG" -o free-nodes || { echo "下载失败"; exit 1; }
          echo "下载完成，保存为 free-nodes"

      # 从https://github.com/ggborr/FREEE-VPN上下载节点文件
      - name: 从ggborr的readme.md中找下载链接并下载文件
        run: |
          url='https://raw.githubusercontent.com/ggborr/FREEE-VPN/main/README.md'
          PREFIX='https://raw.githubusercontent.com/ggborr/FREEE-VPN'
          content=$(curl -s --fail "$url") || { echo "Error: failed to download $url"; exit 1; }
          LATEST_TAG=$(echo "$content" | grep -F "$PREFIX"  | head -1 | grep -o "https://[^ ]*" | sed 's/`$//')
          if [ -z "$LATEST_TAG" ]; then
            echo "未找到下载链接"
          else
            echo "下载链接: $LATEST_TAG"
          fi
          
          curl -s -L --fail "$LATEST_TAG" -o ggborr || { echo "下载失败"; exit 1; }
          echo "下载完成，保存为 ggborr"
            
      - name: Commit & Push
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "🔄 $(date +'%Y-%m-%d %H:%M:%S')"
          git push